export const playersJSON = [
  {
    id: 0,
    name: 'K. Mbappé',
    firstname: 'Kylian',
    lastname: 'Mbappé Lottin',
    age: 23,
    birth: {
      date: '1998-12-20',
      place: 'Paris',
      country: 'France',
    },
    nationality: 'France',
    height: '178 cm',
    weight: '73 kg',
    injured: false,
    photo: 'https://media.api-sports.io/football/players/278.png',
  },
  {
    id: 1,
    name: 'W. Ben Yedder',
    firstname: 'Wissam',
    lastname: 'Ben Yedder',
    age: 31,
    birth: {
      date: '1990-08-12',
      place: 'Sarcelles',
      country: 'France',
    },
    nationality: 'France',
    height: '170 cm',
    weight: '68 kg',
    injured: false,
    photo: 'https://media.api-sports.io/football/players/2059.png',
  },
  {
    id: 2,
    name: 'M. Dembélé',
    firstname: 'Moussa',
    lastname: 'Dembélé',
    age: 25,
    birth: {
      date: '1996-07-12',
      place: 'Pontoise',
      country: 'France',
    },
    nationality: 'France',
    height: '183 cm',
    weight: '73 kg',
    injured: false,
    photo: 'https://media.api-sports.io/football/players/666.png',
  },
];
